# Generated by Django 2.2.7 on 2020-10-24 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Link_a', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Singer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_Name', models.CharField(max_length=100)),
                ('Link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.Link')),
                ('Singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.Singer')),
            ],
        ),
    ]
